# 02. geolocation 대표좌표와 거리 계산 (Day 2)
**목적**: 우편번호별 대표좌표를 만들고, 고객·셀러 사이의 거리(distance_km)를 계산한다. 모집단 기준 테이블(base)도 여기서 만든다.

In [1]:
# 참고: 아래 셀에서 만드는 테이블(base, geo_clean, geo_rep, zip_status, item_lvl)은 재실행하면 목록에 함께 보임
import duckdb

con = duckdb.connect("data/interim/olist.duckdb")
con.execute("SHOW TABLES").df().name.tolist()

['base',
 'cat_tr',
 'chk',
 'customers',
 'geo_clean',
 'geo_rep',
 'geolocation',
 'item_base',
 'item_lvl',
 'master',
 'ord_agg',
 'ord_pay',
 'ord_sum',
 'order_items',
 'order_payments',
 'order_reviews',
 'orders',
 'products',
 'rep_dist',
 'rep_price',
 'rev',
 'sellers',
 'zip_status']

In [2]:
con.execute("""
CREATE OR REPLACE TABLE base AS
SELECT order_id, customer_id, order_status,
       order_purchase_timestamp, order_approved_at,
       order_delivered_customer_date, order_estimated_delivery_date,
       CASE WHEN CAST(order_delivered_customer_date AS DATE)
                 > CAST(order_estimated_delivery_date AS DATE) THEN 1 ELSE 0 END AS late
FROM orders
WHERE order_delivered_customer_date IS NOT NULL
  AND order_purchase_timestamp >= '2017-01-01'
  AND order_purchase_timestamp <  '2018-09-01'
""")

con.execute("""
SELECT COUNT(*) AS n_orders, COUNT(DISTINCT order_id) AS n_unique,
       SUM(late) AS n_late, ROUND(100.0 * AVG(late), 2) AS late_pct
FROM base
""").df()

   n_orders  n_unique  n_late  late_pct
0     96204     96204  6532.0      6.79

In [3]:
display(con.execute("DESCRIBE geolocation").df()[["column_name", "column_type"]])

con.execute("""
SELECT COUNT(*) AS n_rows,
       MIN(geolocation_lat) AS min_lat, MAX(geolocation_lat) AS max_lat,
       MIN(geolocation_lng) AS min_lng, MAX(geolocation_lng) AS max_lng
FROM geolocation
""").df()

                   column_name column_type
0  geolocation_zip_code_prefix     INTEGER
1              geolocation_lat      DOUBLE
2              geolocation_lng      DOUBLE
3             geolocation_city     VARCHAR
4            geolocation_state     VARCHAR

    n_rows    min_lat    max_lat     min_lng     max_lng
0  1000163 -36.605374  45.065933 -101.466766  121.105394

In [4]:
con.execute("""
SELECT COUNT(*) AS n_zip,
       MIN(n) AS min_rows, MEDIAN(n) AS median_rows,
       ROUND(AVG(n), 1) AS mean_rows, MAX(n) AS max_rows,
       SUM(CASE WHEN n = 1 THEN 1 ELSE 0 END) AS zips_with_1_row
FROM (SELECT geolocation_zip_code_prefix, COUNT(*) AS n
      FROM geolocation GROUP BY geolocation_zip_code_prefix)
""").df()

   n_zip  min_rows  median_rows  mean_rows  max_rows  zips_with_1_row
0  19015         1         29.0       52.6      1146           1043.0

In [5]:
con.execute("""
SELECT geolocation_state AS state, COUNT(*) AS n_rows,
       COUNT(DISTINCT geolocation_zip_code_prefix) AS n_zips,
       ROUND(MIN(geolocation_lat), 1) AS min_lat, ROUND(MAX(geolocation_lat), 1) AS max_lat,
       ROUND(MIN(geolocation_lng), 1) AS min_lng, ROUND(MAX(geolocation_lng), 1) AS max_lng
FROM geolocation
WHERE NOT (geolocation_lat BETWEEN -34 AND 6 AND geolocation_lng BETWEEN -74 AND -28)
GROUP BY geolocation_state ORDER BY n_rows DESC
""").df()

   state  n_rows  n_zips  min_lat  max_lat  min_lng  max_lng
0     PA       7       3     38.7     42.4     -9.1     -6.9
1     RJ       5       4    -34.6     43.7    -58.7     13.8
2     RS       4       2    -36.6     14.6    -64.3    121.1
3     BA       4       3    -34.6     39.0    -58.9     -4.9
4     PR       3       2     39.1     42.2     -9.4     -8.7
5     MG       2       1     26.0     26.0    -98.1    -98.1
6     ES       2       1     21.7     29.4   -101.5    -98.5
7     AL       1       1     45.1     45.1      9.3      9.3
8     MT       1       1     38.8     38.8     -9.4     -9.4
9     SP       1       1     28.0     28.0    -15.5    -15.5
10    PB       1       1     41.4     41.4     -8.7     -8.7

In [6]:
con.execute("""
SELECT geolocation_state AS state, geolocation_city AS city, COUNT(*) AS n_rows,
       ROUND(AVG(geolocation_lat), 2) AS avg_lat, ROUND(AVG(geolocation_lng), 2) AS avg_lng
FROM geolocation
WHERE geolocation_lat BETWEEN -34 AND 6 AND geolocation_lng > -34 AND geolocation_lng <= -28
GROUP BY geolocation_state, geolocation_city
""").df()

  state                 city  n_rows  avg_lat  avg_lng
0    PE  fernando de noronha      11    -3.85   -32.41

## 범위 밖 좌표 제거 (D-09)
브라질 범위(위도 -34~6, 경도 -74~-28) 밖 좌표를 제거한다. 경도 -28은 페르난두 지 노로냐 섬(경도 약 -32.4)처럼 브라질령 섬을 포함하기 위한 값이다.

In [7]:
# [셀 7] geo_clean 생성 → 기대: 1,000,163 / 1,000,132 / 19,011
con.execute("""
CREATE OR REPLACE TABLE geo_clean AS
SELECT * FROM geolocation
WHERE geolocation_lat BETWEEN -34 AND 6
  AND geolocation_lng BETWEEN -74 AND -28
""")

con.execute("""
SELECT (SELECT COUNT(*) FROM geolocation) AS n_before,
       COUNT(*) AS n_after,
       COUNT(DISTINCT geolocation_zip_code_prefix) AS n_zip_after
FROM geo_clean
""").df()

   n_before  n_after  n_zip_after
0   1000163  1000132        19011

## 대표좌표: 평균 vs 중앙값 근거 (D-10)
박스 필터를 통과해도 브라질 안에서 엉뚱한 곳에 찍힌 좌표가 남는다. 평균은 그런 좌표에 끌려가고 중앙값은 잘 안 움직이므로, 대표좌표는 중앙값으로 정한다. 아래는 그 근거 숫자다.

In [8]:
# [셀 8] 평균 vs 중앙값 근거
# (a) 우편번호별 평균 대표점 vs 중앙값 대표점의 거리 차이 → 기대: 19,011 / 223 / 96 / 1,120
display(con.execute("""
WITH c AS (
  SELECT geolocation_zip_code_prefix AS zip,
         AVG(geolocation_lat) AS mean_lat, AVG(geolocation_lng) AS mean_lng,
         MEDIAN(geolocation_lat) AS med_lat, MEDIAN(geolocation_lng) AS med_lng
  FROM geo_clean GROUP BY geolocation_zip_code_prefix),
d AS (
  SELECT zip, 2 * 6371.0088 * asin(sqrt(
           pow(sin(radians(med_lat - mean_lat) / 2), 2) +
           cos(radians(mean_lat)) * cos(radians(med_lat)) *
           pow(sin(radians(med_lng - mean_lng) / 2), 2))) AS km
  FROM c)
SELECT COUNT(*) AS n_zip,
       SUM(CASE WHEN km > 10 THEN 1 ELSE 0 END) AS gt10km,
       SUM(CASE WHEN km > 50 THEN 1 ELSE 0 END) AS gt50km,
       ROUND(MAX(km), 0) AS max_km
FROM d
""").df())

# (b) 평균 대표점에서 가장 먼 좌표까지의 거리가 200km를 넘는 우편번호 → 기대: 19,011 / 207 / 2,994
display(con.execute("""
WITH c AS (
  SELECT geolocation_zip_code_prefix AS zip,
         AVG(geolocation_lat) AS mean_lat, AVG(geolocation_lng) AS mean_lng
  FROM geo_clean GROUP BY geolocation_zip_code_prefix),
d AS (
  SELECT g.geolocation_zip_code_prefix AS zip,
         2 * 6371.0088 * asin(sqrt(
           pow(sin(radians(g.geolocation_lat - c.mean_lat) / 2), 2) +
           cos(radians(c.mean_lat)) * cos(radians(g.geolocation_lat)) *
           pow(sin(radians(g.geolocation_lng - c.mean_lng) / 2), 2))) AS km
  FROM geo_clean g JOIN c ON c.zip = g.geolocation_zip_code_prefix),
m AS (SELECT zip, MAX(km) AS max_km FROM d GROUP BY zip)
SELECT COUNT(*) AS n_zip,
       SUM(CASE WHEN max_km > 200 THEN 1 ELSE 0 END) AS zips_with_point_gt200km,
       ROUND(MAX(max_km), 0) AS max_km
FROM m
""").df())

   n_zip  gt10km  gt50km  max_km
0  19011   223.0    96.0  1120.0

   n_zip  zips_with_point_gt200km  max_km
0  19011                    207.0  2994.0

## 대표좌표 테이블 geo_rep
우편번호당 1행(중앙값 위·경도 + 관측치 수 n). 조인 전에 이 표부터 만들어야 행이 폭발하지 않는다.

In [9]:
# [셀 9] geo_rep 생성 → 기대: 19,011 / 19,011 / 1,042 (앞 두 숫자가 같아야 우편번호당 1행)
con.execute("""
CREATE OR REPLACE TABLE geo_rep AS
SELECT geolocation_zip_code_prefix AS zip,
       MEDIAN(geolocation_lat) AS lat,
       MEDIAN(geolocation_lng) AS lng,
       COUNT(*) AS n
FROM geo_clean
GROUP BY geolocation_zip_code_prefix
""")

con.execute("""
SELECT COUNT(*) AS n_rows, COUNT(DISTINCT zip) AS n_zip,
       SUM(CASE WHEN n = 1 THEN 1 ELSE 0 END) AS zips_with_1_row
FROM geo_rep
""").df()

   n_rows  n_zip  zips_with_1_row
0   19011  19011           1042.0

## 매칭률 4방향 분해 (D-04)
고객·셀러 우편번호가 geo_rep에 없는 경우를 우편번호·행·base 주문 단위로 센다.
- **A**: geolocation 원본에 우편번호 자체가 없음
- **B**: 좌표는 있었는데 범위 필터로 전부 제거됨

미매칭은 NULL로 두고, 대체(동일 주 평균 + 결측 더미)는 학습 구간이 정해진 뒤에 한다.

In [10]:
# [셀 10] 매칭률 → 기대: customer zip 14,994/158/157/1, row 99,441/279/278/1, base_order 96,204/265/264/1
#                       seller zip 2,246/7/7/0, row 3,095/7/7/0, base_order 96,204/217/217/0
#                       거리 계산 불가 base 주문 96,204 / 481 / 0.5
con.execute("""
CREATE OR REPLACE TABLE zip_status AS
SELECT z.zip,
       CASE WHEN r.zip IS NOT NULL THEN 'ok'
            WHEN g.zip IS NOT NULL THEN 'B_filtered'
            ELSE 'A_not_in_geolocation' END AS status
FROM (SELECT customer_zip_code_prefix AS zip FROM customers
      UNION
      SELECT seller_zip_code_prefix FROM sellers) z
LEFT JOIN geo_rep r ON r.zip = z.zip
LEFT JOIN (SELECT DISTINCT geolocation_zip_code_prefix AS zip FROM geolocation) g ON g.zip = z.zip
""")

display(con.execute("""
SELECT 'customer' AS side, 'zip' AS level, COUNT(*) AS total,
       CAST(SUM(CAST(status <> 'ok' AS INTEGER)) AS INTEGER) AS unmatched,
       CAST(SUM(CAST(status = 'A_not_in_geolocation' AS INTEGER)) AS INTEGER) AS A,
       CAST(SUM(CAST(status = 'B_filtered' AS INTEGER)) AS INTEGER) AS B
FROM (SELECT DISTINCT customer_zip_code_prefix AS zip FROM customers) t JOIN zip_status USING (zip)
UNION ALL
SELECT 'customer', 'row', COUNT(*),
       CAST(SUM(CAST(status <> 'ok' AS INTEGER)) AS INTEGER),
       CAST(SUM(CAST(status = 'A_not_in_geolocation' AS INTEGER)) AS INTEGER),
       CAST(SUM(CAST(status = 'B_filtered' AS INTEGER)) AS INTEGER)
FROM customers c JOIN zip_status s ON s.zip = c.customer_zip_code_prefix
UNION ALL
SELECT 'customer', 'base_order', COUNT(*),
       CAST(SUM(CAST(status <> 'ok' AS INTEGER)) AS INTEGER),
       CAST(SUM(CAST(status = 'A_not_in_geolocation' AS INTEGER)) AS INTEGER),
       CAST(SUM(CAST(status = 'B_filtered' AS INTEGER)) AS INTEGER)
FROM base b JOIN customers c USING (customer_id) JOIN zip_status s ON s.zip = c.customer_zip_code_prefix
UNION ALL
SELECT 'seller', 'zip', COUNT(*),
       CAST(SUM(CAST(status <> 'ok' AS INTEGER)) AS INTEGER),
       CAST(SUM(CAST(status = 'A_not_in_geolocation' AS INTEGER)) AS INTEGER),
       CAST(SUM(CAST(status = 'B_filtered' AS INTEGER)) AS INTEGER)
FROM (SELECT DISTINCT seller_zip_code_prefix AS zip FROM sellers) t JOIN zip_status USING (zip)
UNION ALL
SELECT 'seller', 'row', COUNT(*),
       CAST(SUM(CAST(status <> 'ok' AS INTEGER)) AS INTEGER),
       CAST(SUM(CAST(status = 'A_not_in_geolocation' AS INTEGER)) AS INTEGER),
       CAST(SUM(CAST(status = 'B_filtered' AS INTEGER)) AS INTEGER)
FROM sellers s JOIN zip_status z ON z.zip = s.seller_zip_code_prefix
UNION ALL
SELECT 'seller', 'base_order', COUNT(*), CAST(SUM(any_bad) AS INTEGER),
       CAST(SUM(any_a) AS INTEGER), CAST(SUM(any_b) AS INTEGER)
FROM (SELECT b.order_id,
             MAX(CAST(z.status <> 'ok' AS INTEGER)) AS any_bad,
             MAX(CAST(z.status = 'A_not_in_geolocation' AS INTEGER)) AS any_a,
             MAX(CAST(z.status = 'B_filtered' AS INTEGER)) AS any_b
      FROM base b
      JOIN order_items i ON i.order_id = b.order_id
      JOIN sellers s ON s.seller_id = i.seller_id
      JOIN zip_status z ON z.zip = s.seller_zip_code_prefix
      GROUP BY b.order_id)
""").df())

# 고객 또는 (어떤 아이템의) 셀러가 미매칭이라 거리를 못 구하는 base 주문
display(con.execute("""
SELECT COUNT(*) AS n_base_orders, SUM(bad) AS n_no_distance, ROUND(100.0 * AVG(bad), 2) AS pct
FROM (SELECT b.order_id,
             MAX(CASE WHEN zc.status <> 'ok' OR zs.status <> 'ok' THEN 1 ELSE 0 END) AS bad
      FROM base b
      JOIN customers c USING (customer_id)
      JOIN order_items i ON i.order_id = b.order_id
      JOIN sellers s ON s.seller_id = i.seller_id
      JOIN zip_status zc ON zc.zip = c.customer_zip_code_prefix
      JOIN zip_status zs ON zs.zip = s.seller_zip_code_prefix
      GROUP BY b.order_id)
""").df())

       side       level  total  unmatched    A  B
0  customer         zip  14994        158  157  1
1  customer         row  99441        279  278  1
2  customer  base_order  96204        265  264  1
3    seller         zip   2246          7    7  0
4    seller         row   3095          7    7  0
5    seller  base_order  96204        217  217  0

   n_base_orders  n_no_distance  pct
0          96204          481.0  0.5

## item_lvl: 아이템 단위 distance_km (하버사인)
고객·셀러 대표좌표로 두 점 사이 직선거리를 구한다. `LEFT JOIN`이라 좌표가 없으면 행은 남고 `distance_km`만 NULL이 된다. 조인 전후 행 수(112,650)가 같아야 한다.

`item_lvl`은 기간·배송 여부와 무관하게 order_items 전체(112,650행) 기준이다. 분석 모집단(base)은 Day 3에서 조인할 때 한정한다.

In [11]:
# [셀 11] item_lvl 생성 → 기대: 112,650 / 112,650 / 112,095 / 555 (앞 두 숫자가 같아야 함)
con.execute("""
CREATE OR REPLACE TABLE item_lvl AS
SELECT i.order_id, i.order_item_id, i.product_id, i.seller_id, i.price, i.freight_value,
       c.customer_zip_code_prefix AS customer_zip, s.seller_zip_code_prefix AS seller_zip,
       rc.n AS c_n, rs.n AS s_n,
       2 * 6371.0088 * asin(sqrt(
           pow(sin(radians(rs.lat - rc.lat) / 2), 2) +
           cos(radians(rc.lat)) * cos(radians(rs.lat)) *
           pow(sin(radians(rs.lng - rc.lng) / 2), 2))) AS distance_km
FROM order_items i
JOIN orders    o ON o.order_id    = i.order_id
JOIN customers c ON c.customer_id = o.customer_id
JOIN sellers   s ON s.seller_id   = i.seller_id
LEFT JOIN geo_rep rc ON rc.zip = c.customer_zip_code_prefix
LEFT JOIN geo_rep rs ON rs.zip = s.seller_zip_code_prefix
""")

con.execute("""
SELECT (SELECT COUNT(*) FROM order_items) AS n_before, COUNT(*) AS n_after,
       COUNT(distance_km) AS n_with_distance, COUNT(*) - COUNT(distance_km) AS n_null
FROM item_lvl
""").df()

   n_before  n_after  n_with_distance  n_null
0    112650   112650           112095     555

## 거리 분포 검증
이상 신호는 4,500km 초과(브라질 본토 안 최장 직선거리가 4,300km대). 정상 값도 3,500km대까지 나오므로 "수천 km"를 기준으로 삼지 않는다.

In [12]:
# [셀 12] 거리 분포·공식 검증·n=1 우편번호·셀러 지역 집중도
# (a) 기대: min 0 / p25 183 / median 431.7 / p75 792 / p90 1,451 / max 3,579 / 4,500km 초과 0건
display(con.execute("""
SELECT ROUND(MIN(distance_km), 1) AS min_km,
       ROUND(QUANTILE_CONT(distance_km, 0.25), 0) AS p25,
       ROUND(MEDIAN(distance_km), 1) AS median_km,
       ROUND(QUANTILE_CONT(distance_km, 0.75), 0) AS p75,
       ROUND(QUANTILE_CONT(distance_km, 0.90), 0) AS p90,
       ROUND(MAX(distance_km), 0) AS max_km,
       SUM(CASE WHEN distance_km > 4500 THEN 1 ELSE 0 END) AS n_gt_4500km
FROM item_lvl
""").df())

# (b) 공식 검증: 상파울루 ↔ 리우 → 기대: 360.7
display(con.execute("""
SELECT ROUND(2 * 6371.0088 * asin(sqrt(
         pow(sin(radians(-22.9068 - (-23.5505)) / 2), 2) +
         cos(radians(-23.5505)) * cos(radians(-22.9068)) *
         pow(sin(radians(-43.1729 - (-46.6333)) / 2), 2))), 1) AS sao_paulo_to_rio_km
""").df())

# (c) 관측치가 1개뿐인 우편번호에 기대는 아이템 → 기대: 539 / 0.48
display(con.execute("""
SELECT SUM(CASE WHEN c_n = 1 OR s_n = 1 THEN 1 ELSE 0 END) AS items_with_n1_zip,
       ROUND(100.0 * AVG(CASE WHEN c_n = 1 OR s_n = 1 THEN 1 ELSE 0 END), 2) AS pct
FROM item_lvl
""").df())

# (d) 셀러 지역 집중도 → 기대: 셀러 수 기준 SP 1,849(59.7%) / 아이템 기준 SP 80,342(71.3%)
display(con.execute("""
SELECT seller_state, COUNT(*) AS n_sellers,
       ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 1) AS pct_sellers
FROM sellers GROUP BY seller_state ORDER BY n_sellers DESC LIMIT 5
""").df())
display(con.execute("""
SELECT s.seller_state, COUNT(*) AS n_items,
       ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 1) AS pct_items
FROM order_items i JOIN sellers s USING (seller_id)
GROUP BY s.seller_state ORDER BY n_items DESC LIMIT 5
""").df())

   min_km    p25  median_km    p75     p90  max_km  n_gt_4500km
0     0.0  183.0      431.7  792.0  1451.0  3579.0          0.0

   sao_paulo_to_rio_km
0                360.7

   items_with_n1_zip   pct
0              539.0  0.48

  seller_state  n_sellers  pct_sellers
0           SP       1849         59.7
1           PR        349         11.3
2           MG        244          7.9
3           SC        190          6.1
4           RJ        171          5.5

  seller_state  n_items  pct_items
0           SP    80342       71.3
1           MG     8827        7.8
2           PR     8671        7.7
3           RJ     4818        4.3
4           SC     4075        3.6

## 보충: 미매칭 셀러의 주문 수 (D-04)
미매칭 셀러 7곳이 어느 정도 규모의 셀러인지 본다. 평균만 비교하면 분포가 치우쳐 있어 오해할 수 있으므로, 셀러별 주문 수와 전체 분포(중앙값, 순위)를 함께 확인한다.

In [13]:
# [보충] 미매칭 셀러 7곳의 base 주문 수 (D-04)
# (a) 기대: 127 / 45 / 34 / 6 / 2 / 2 / 1 (합 217)
display(con.execute("""
SELECT s.seller_id, s.seller_zip_code_prefix AS zip, COUNT(DISTINCT b.order_id) AS n_orders
FROM sellers s
JOIN order_items i ON i.seller_id = s.seller_id
JOIN base b ON b.order_id = i.order_id
JOIN zip_status z ON z.zip = s.seller_zip_code_prefix
WHERE z.status <> 'ok'
GROUP BY s.seller_id, s.seller_zip_code_prefix
ORDER BY n_orders DESC
""").df())

# (b) 전체 셀러 주문 수 분포와 미매칭 최대 셀러(127건)의 순위
#     기대: 2,945 / 평균 33.12 / 중앙값 7 / 최대 1,819 / 127 / 159곳 / 5.4%
con.execute("""
WITH sc AS (
  SELECT i.seller_id, COUNT(DISTINCT b.order_id) AS n_orders
  FROM base b JOIN order_items i ON i.order_id = b.order_id
  GROUP BY i.seller_id),
um AS (
  SELECT sc.seller_id, sc.n_orders
  FROM sc JOIN sellers s USING (seller_id)
          JOIN zip_status z ON z.zip = s.seller_zip_code_prefix
  WHERE z.status <> 'ok')
SELECT (SELECT COUNT(*) FROM sc) AS n_sellers,
       ROUND((SELECT AVG(n_orders) FROM sc), 2) AS mean_orders,
       (SELECT MEDIAN(n_orders) FROM sc) AS median_orders,
       (SELECT MAX(n_orders) FROM sc) AS max_orders,
       (SELECT MAX(n_orders) FROM um) AS top_unmatched,
       (SELECT COUNT(*) FROM sc WHERE n_orders >= (SELECT MAX(n_orders) FROM um)) AS sellers_ge_top,
       ROUND(100.0 * (SELECT COUNT(*) FROM sc WHERE n_orders >= (SELECT MAX(n_orders) FROM um))
             / (SELECT COUNT(*) FROM sc), 1) AS pct_ge_top
""").df()

                          seller_id    zip  n_orders
0  2e90cb1677d35cfe24eef47d441b7c87   2285       127
1  870d0118f7a9d85960f29ad89d5d989a  37708        45
2  42bde9fef835393bb8a8849cb6b7f245  71551        34
3  5962468f885ea01a1b6a97a218797b0a  82040         6
4  2aafae69bf4c41fbd94053d9413e87ee  91901         2
5  0b3f27369a4d8df98f7eb91077e438ac   7412         2
6  2a50b7ee5aebecc6fd0ff9784a4747d6  72580         1

,n_sellers,mean_orders,median_orders,max_orders,top_unmatched,sellers_ge_top,pct_ge_top
0,2945,33.12,7.0,1819,127,159,5.4

## 보충: 우측절단·날짜 내적 일관성 검증 (2026-09-23 추가)
1주차 재검토 과정에서 두 가지를 추가로 확인한다.
1. **우측절단(right-censoring) 의심**: 분석기간 마지막 달(2018-08)에 구매한 주문 중, 배송이 오래 걸리는(=지연 후보) 주문이 데이터 추출 시점까지 도착 안 해서 `order_delivered_customer_date IS NULL`로 `base`에서 제외됐을 가능성.
2. **날짜 컬럼 내적 일관성**: `구매일 ≤ 승인일 ≤ 출고일 ≤ 도착일` 순서가 실제로 지켜지는지.

In [14]:
# [보충 A] 8월 일별 도착일 결측률 → 우측절단(right-censoring) 의심 구간 확인
con.execute("""
SELECT CAST(order_purchase_timestamp AS DATE) AS d,
       COUNT(*) AS n,
       SUM(CASE WHEN order_delivered_customer_date IS NULL THEN 1 ELSE 0 END) AS n_null,
       ROUND(100.0*AVG(CASE WHEN order_delivered_customer_date IS NULL THEN 1 ELSE 0 END), 1) AS pct_null
FROM orders
WHERE order_purchase_timestamp >= '2018-08-01' AND order_purchase_timestamp < '2018-09-01'
GROUP BY d ORDER BY d
""").df()

            d    n  n_null  pct_null
0  2018-08-01  311     5.0       1.6
1  2018-08-02  302    10.0       3.3
2  2018-08-03  314     6.0       1.9
3  2018-08-04  245     9.0       3.7
4  2018-08-05  276     7.0       2.5
5  2018-08-06  372     9.0       2.4
6  2018-08-07  370    17.0       4.6
7  2018-08-08  316     6.0       1.9
8  2018-08-09  289     9.0       3.1
9  2018-08-10  256     7.0       2.7
10 2018-08-11  188     3.0       1.6
11 2018-08-12  197     6.0       3.0
12 2018-08-13  292     8.0       2.7
13 2018-08-14  316     5.0       1.6
14 2018-08-15  288     6.0       2.1
15 2018-08-16  320     4.0       1.3
16 2018-08-17  257     8.0       3.1
17 2018-08-18  198     5.0       2.5
18 2018-08-19  204     0.0       0.0
19 2018-08-20  256     5.0       2.0
20 2018-08-21  243     5.0       2.1
21 2018-08-22  187     2.0       1.1
22 2018-08-23  144     2.0       1.4
23 2018-08-24   99     3.0       3.0
24 2018-08-25   69     0.0       0.0
25 2018-08-26   73     0.0       0.0
26 2018-08-27   67     1.0       1.5
27 2018-08-28   44     5.0      11.4
28 2018-08-29   14     3.0      21.4
29 2018-08-30    4     4.0     100.0
30 2018-08-31    1     1.0     100.0

In [15]:
# 8/1~27 vs 8/28~31 비교, 6월(정상 구간)과 대조
con.execute("""
SELECT CASE WHEN CAST(order_purchase_timestamp AS DATE) < '2018-08-28' THEN '8/1-27' ELSE '8/28-31' END AS period,
       COUNT(*) AS n, SUM(CASE WHEN order_delivered_customer_date IS NULL THEN 1 ELSE 0 END) AS n_null,
       ROUND(100.0*AVG(CASE WHEN order_delivered_customer_date IS NULL THEN 1 ELSE 0 END), 1) AS pct_null
FROM orders
WHERE order_purchase_timestamp >= '2018-08-01' AND order_purchase_timestamp < '2018-09-01'
GROUP BY period
""").df()

    period     n  n_null  pct_null
0   8/1-27  6449   148.0       2.3
1  8/28-31    63    13.0      20.6

In [16]:
con.execute("""
SELECT COUNT(*) AS n, SUM(CASE WHEN order_delivered_customer_date IS NULL THEN 1 ELSE 0 END) AS n_null,
       ROUND(100.0*AVG(CASE WHEN order_delivered_customer_date IS NULL THEN 1 ELSE 0 END), 1) AS pct_null
FROM orders
WHERE order_purchase_timestamp >= '2018-06-01' AND order_purchase_timestamp < '2018-07-01'
""").df()

      n  n_null  pct_null
0  6167    71.0       1.2

In [17]:
# [보충 B] 8/28~31 결측 13건의 order_status 분포 → "아직 배송 중"인지 "취소"인지 구분
con.execute("""
SELECT order_status, COUNT(*) AS n_total,
       SUM(CASE WHEN order_delivered_customer_date IS NULL THEN 1 ELSE 0 END) AS n_null
FROM orders
WHERE order_purchase_timestamp >= '2018-08-28' AND order_purchase_timestamp < '2018-09-01'
GROUP BY order_status ORDER BY n_total DESC
""").df()

  order_status  n_total  n_null
0    delivered       50     0.0
1     canceled       13    13.0

In [18]:
# canceled 비율이 이 4일 구간에서 유독 높은지 기준선과 비교
con.execute("""
SELECT '8/28-31' AS period,
       ROUND(100.0*AVG(CASE WHEN order_status='canceled' THEN 1 ELSE 0 END), 1) AS pct_canceled
FROM orders WHERE order_purchase_timestamp >= '2018-08-28' AND order_purchase_timestamp < '2018-09-01'
UNION ALL
SELECT '8/1-27', ROUND(100.0*AVG(CASE WHEN order_status='canceled' THEN 1 ELSE 0 END), 1)
FROM orders WHERE order_purchase_timestamp >= '2018-08-01' AND order_purchase_timestamp < '2018-08-28'
UNION ALL
SELECT '전체기간(2017-01~2018-08)', ROUND(100.0*AVG(CASE WHEN order_status='canceled' THEN 1 ELSE 0 END), 2)
FROM orders WHERE order_purchase_timestamp >= '2017-01-01' AND order_purchase_timestamp < '2018-09-01'
""").df()

                  period  pct_canceled
0                8/28-31         20.60
1                 8/1-27          1.10
2  전체기간(2017-01~2018-08)          0.59

In [19]:
# [보충 C] 날짜 컬럼 내적 일관성 검증 — 시간 순서가 뒤집힌 행이 있는지
con.execute("""
SELECT
  SUM(CASE WHEN order_delivered_carrier_date < order_purchase_timestamp THEN 1 ELSE 0 END) AS carrier_lt_purchase,
  SUM(CASE WHEN order_delivered_customer_date < order_delivered_carrier_date THEN 1 ELSE 0 END) AS delivered_lt_carrier,
  SUM(CASE WHEN order_delivered_customer_date < order_approved_at THEN 1 ELSE 0 END) AS delivered_lt_approved,
  SUM(CASE WHEN order_approved_at < order_purchase_timestamp THEN 1 ELSE 0 END) AS approved_lt_purchase
FROM orders
""").df()

,carrier_lt_purchase,delivered_lt_carrier,delivered_lt_approved,approved_lt_purchase
0,166.0,23.0,61.0,0.0

In [20]:
# late 계산에 실제로 쓰는 두 컬럼(purchase, delivered_customer)만 따로 확인 → 여기 위반이 0이어야 base/late가 안전
con.execute("""
SELECT SUM(CASE WHEN order_delivered_customer_date < order_purchase_timestamp THEN 1 ELSE 0 END) AS delivered_lt_purchase
FROM orders WHERE order_delivered_customer_date IS NOT NULL
""").df()

   delivered_lt_purchase
0                    0.0

**해석**
- 8/1~27은 결측률 2.3%(6월 1.2%와 비슷한 수준)로 정상. **8/28~31 나흘만 20.6%**(63건 중 13건)로 튀어 오름 → 이 나흘만 우측절단 의심 구간
- 근데 그 13건을 order_status로 까보면 **전부 `canceled`이고 `shipped`·`invoiced`(진행중) 상태는 0건**. 즉 "아직 배송 중이라 도착일이 안 찍힌" 진짜 절단 케이스가 아니라, **이 나흘 구간에 취소 주문이 몰려 있는 현상**(같은 구간 canceled 비율 20.6% vs 8/1~27 1.1% vs 전체기간 0.59%)
- canceled 주문은 시간이 아무리 지나도 도착일이 생기지 않으므로(영구 결측), '조금만 더 기다리면 데이터가 생길 절단'이 아니라 **정의상 원래도 배송완료 모집단에서 빠져야 하는 주문**. 8/28~31 나흘 자체가 표본이 워낙 작아서(63건) 비율이 크게 튀어 보이는 것도 있음
- 결론: 이번 검증 범위(8월 말 나흘)에서는 걱정했던 형태의 우측절단(진행중 주문의 도착일 미기록)은 **발견되지 않음**. 다만 이 4일 구간의 canceled 집중 현상 자체는 원인 불명이라 월별 추이 해석 시 8/28~31은 별도 표시하거나 제외 권장 — decisions.md에 D-17로 기록할 것
- 날짜 내적 일관성: `carrier_date < purchase` 166건, `delivered < carrier` 23건, `delivered < approved` 61건, `approved < purchase` 0건. 전부 `late` 계산엔 안 쓰는 컬럼 조합
- **`late` 계산에 실제로 쓰는 두 컬럼(purchase, delivered_customer) 사이엔 위반 0건** → 지금까지 만든 `base`·`late`·`master`는 이 문제로부터 안전함. 166/23/61건은 `order_approved_at`·`order_delivered_carrier_date`를 파생변수로 쓸 Day4~6 전에 처리 방침(제외/원인규명/표시) 결정 필요

## 재검토 (2026-09-23, 위 해석을 정정함)
위 "보충 A~C" 결론("우측절단 없음, canceled 집중 현상일 뿐")은 **8/28~31 나흘, 그것도 결측된 13건만** 들여다본 결과였다. 범위를 넓혀서 1) 요일 효과인지, 2) **base에 실제로 남은(결측 아닌) 주문들의 late율 자체가 왜곡됐는지**를 추가로 확인한다.

In [21]:
# [보충 D, 2026-09-23 재검토] 같은 요일끼리 대조 — 주문건수 붕괴가 요일 효과가 아닌지 확인
con.execute("""
SELECT DAYNAME(CAST(order_purchase_timestamp AS DATE)) AS dow,
       CAST(order_purchase_timestamp AS DATE) AS d, COUNT(*) AS n
FROM orders WHERE order_purchase_timestamp >= '2018-08-15' AND order_purchase_timestamp < '2018-08-29'
GROUP BY dow, d ORDER BY d
""").df()

          dow          d    n
0   Wednesday 2018-08-15  288
1    Thursday 2018-08-16  320
2      Friday 2018-08-17  257
3    Saturday 2018-08-18  198
4      Sunday 2018-08-19  204
5      Monday 2018-08-20  256
6     Tuesday 2018-08-21  243
7   Wednesday 2018-08-22  187
8    Thursday 2018-08-23  144
9      Friday 2018-08-24   99
10   Saturday 2018-08-25   69
11     Sunday 2018-08-26   73
12     Monday 2018-08-27   67
13    Tuesday 2018-08-28   44

In [22]:
# [보충 E] 8월을 구간별로 쪼개서 base 동일 정의로 late율 확인 — 우측절단의 직접 증거
con.execute("""
WITH b AS (
  SELECT order_id, CAST(order_purchase_timestamp AS DATE) AS pd,
         CASE WHEN CAST(order_delivered_customer_date AS DATE) > CAST(order_estimated_delivery_date AS DATE) THEN 1 ELSE 0 END AS late
  FROM orders
  WHERE order_delivered_customer_date IS NOT NULL
    AND order_purchase_timestamp >= '2018-08-01' AND order_purchase_timestamp < '2018-09-01'
)
SELECT CASE WHEN pd < '2018-08-08' THEN '8/1-7'
            WHEN pd < '2018-08-15' THEN '8/8-14'
            WHEN pd < '2018-08-22' THEN '8/15-21'
            WHEN pd < '2018-08-28' THEN '8/22-27'
            ELSE '8/28-31' END AS period,
       COUNT(*) AS n_in_base, SUM(late) AS n_late, ROUND(100.0*AVG(late), 1) AS late_pct
FROM b GROUP BY period ORDER BY period
""").df()

    period  n_in_base  n_late  late_pct
0    8/1-7       2127   237.0      11.1
1  8/15-21       1733    53.0       3.1
2  8/22-27        631     5.0       0.8
3  8/28-31         50     0.0       0.0
4   8/8-14       1810    98.0       5.4

In [23]:
# 7월(비경계 구간) 동일 방식 대조군 — 월말이라서 생기는 일반적 패턴인지 확인
con.execute("""
WITH b AS (
  SELECT order_id, CAST(order_purchase_timestamp AS DATE) AS pd,
         CASE WHEN CAST(order_delivered_customer_date AS DATE) > CAST(order_estimated_delivery_date AS DATE) THEN 1 ELSE 0 END AS late
  FROM orders
  WHERE order_delivered_customer_date IS NOT NULL
    AND order_purchase_timestamp >= '2018-07-01' AND order_purchase_timestamp < '2018-08-01'
)
SELECT CASE WHEN pd < '2018-07-22' THEN '7/1-21' ELSE '7/22-31' END AS period,
       COUNT(*) AS n_in_base, SUM(late) AS n_late, ROUND(100.0*AVG(late), 1) AS late_pct
FROM b GROUP BY period ORDER BY period
""").df()

    period  n_in_base  n_late  late_pct
0   7/1-21       3742   114.0       3.0
1  7/22-31       2414    94.0       3.9

**정정된 해석**
- 요일 대조: 8/15~21(정상주) vs 8/22~28, 7개 요일 전부 예외 없이 급감(수 288→187, 목 320→144, 금 257→99, 토 198→69, 일 204→73, 월 256→67, 화 243→44) → 주말 효과 아니고 구조적 붕괴 맞음
- **결정적 증거**: `base`와 동일 정의(도착일 있는 주문)로 8월을 5구간으로 쪼개 late율을 보면 **8/1-7 11.1% → 8/8-14 5.4% → 8/15-21 3.1% → 8/22-27 0.8% → 8/28-31 0.0%로 월말에 가까울수록 계단식으로 떨어짐**. 7월 대조군은 7/1-21 3.0% vs 7/22-31 3.9%로 이런 패턴이 없음(오히려 소폭 상승) → 8월만의 현상
- 해석: 월말에 가까운 주문일수록 "실제로 아직 배송 중인, 느린(=late 후보인) 주문"이 데이터 추출 시점까지 도착일을 못 찍어 `base`에서 통째로 빠지고, **짧은 시간 안에 이미 끝난 '빠른 배송' 주문만 표본에 남아서 late율이 인위적으로 0%에 가깝게 눌린 것** — 원래 D-17에서 걱정했던 우측절단이 실제로 존재함을 "남아있는 표본의 late율" 기준으로 확인
- **위 "보충 A~C"의 "우측절단 없음" 결론은 폐기.** "8/28~31 결측 13건이 전부 canceled"라는 관찰 자체는 사실이지만, 그것만 보고 절단이 없다고 판단한 게 성급했음 — canceled 여부는 *빠진* 행의 특징일 뿐, *남은* 행이 대표성 있는지는 별도로 확인해야 하는 질문이었음
- 영향 범위: 대략 8/15 이후(넓게 보면 8/8 이후)는 late율이 신뢰 불가. `master`·`base`의 전체 집계(late 6.79% 등)는 이 구간 비중이 작아(전체의 2~3%) 거의 영향 없지만, **Day4 월별 지연율 추이 그래프에서 8월(특히 후반부) 수치를 그대로 해석하면 안 됨**. D-03(테스트 기간) 결정 시 이 구간을 "최근 배송이 좋아진 추세"로 오인하지 않도록 각별히 주의 — decisions.md D-17 정정

## 재정정 근거 (2026-09-23) — 위 결론("아직 배송 중"이 아니라 "canceled 종결+비정상 생존표본")의 실제 검증 셀

In [24]:
# [보충 F, 2026-09-23 재정정] 데이터 추출 시점 상한 확인
con.execute("SELECT MAX(order_delivered_customer_date) AS max_delivered_date FROM orders").df()

   max_delivered_date
0 2018-10-17 13:22:46

In [25]:
# 8/28-31에 delivered로 남은 50건의 소요일(구매→도착, 시각 단위) vs 분석기간 전체 baseline
con.execute("""
SELECT '8/28-31 delivered(생존표본)' AS grp, COUNT(*) AS n,
       ROUND(AVG(EPOCH(order_delivered_customer_date - order_purchase_timestamp))/86400, 2) AS avg_days,
       ROUND(MAX(EPOCH(order_delivered_customer_date - order_purchase_timestamp))/86400, 2) AS max_days
FROM orders
WHERE order_purchase_timestamp >= '2018-08-28' AND order_purchase_timestamp < '2018-09-01'
  AND order_delivered_customer_date IS NOT NULL
UNION ALL
SELECT '분석기간 전체(2017-01~2018-08) baseline', COUNT(*),
       ROUND(AVG(DATE_DIFF('day', order_purchase_timestamp, order_delivered_customer_date)), 2),
       ROUND(QUANTILE_CONT(DATE_DIFF('day', order_purchase_timestamp, order_delivered_customer_date), 0.9), 2)
FROM orders
WHERE order_purchase_timestamp >= '2017-01-01' AND order_purchase_timestamp < '2018-09-01'
  AND order_delivered_customer_date IS NOT NULL
""").df()

                                 grp      n  avg_days  max_days
0            8/28-31 delivered(생존표본)     50      1.76      2.54
1  분석기간 전체(2017-01~2018-08) baseline  96204     12.48     23.00

In [26]:
# 2018년 월별 평균/90%ile 소요일 — 장기 개선 추세가 있는지 확인(있으면 8월 vs 전체평균 비교가 왜곡됨)
con.execute("""
WITH b AS (
  SELECT DATE_TRUNC('month', order_purchase_timestamp) AS m,
         DATE_DIFF('day', order_purchase_timestamp, order_delivered_customer_date) AS lead
  FROM orders WHERE order_delivered_customer_date IS NOT NULL
)
SELECT m, COUNT(*) AS n, ROUND(AVG(lead),1) AS avg_lead, ROUND(QUANTILE_CONT(lead,0.9),1) AS p90_lead
FROM b WHERE m >= '2018-01-01' AND m < '2018-09-01'
GROUP BY m ORDER BY m
""").df()

           m     n  avg_lead  p90_lead
0 2018-01-01  7069      14.0      25.0
1 2018-02-01  6556      16.9      31.0
2 2018-03-01  7003      16.2      32.0
3 2018-04-01  6798      11.4      21.0
4 2018-05-01  6749      11.3      21.0
5 2018-06-01  6096       9.2      16.0
6 2018-07-01  6156       8.9      16.0
7 2018-08-01  6351       7.7      13.0

In [27]:
# 7월(비경계, "정상") 5구간 vs 8월 5구간 — 같은 방식으로 나눠 p90 소요일을 직접 대조 (올바른 대조군)
con.execute("""
WITH b7 AS (
  SELECT CAST(order_purchase_timestamp AS DATE) AS pd,
         DATE_DIFF('day', order_purchase_timestamp, order_delivered_customer_date) AS lead
  FROM orders WHERE order_delivered_customer_date IS NOT NULL
    AND order_purchase_timestamp >= '2018-07-01' AND order_purchase_timestamp < '2018-08-01'
),
b8 AS (
  SELECT CAST(order_purchase_timestamp AS DATE) AS pd,
         DATE_DIFF('day', order_purchase_timestamp, order_delivered_customer_date) AS lead
  FROM orders WHERE order_delivered_customer_date IS NOT NULL
    AND order_purchase_timestamp >= '2018-08-01' AND order_purchase_timestamp < '2018-09-01'
)
SELECT '7월(대조군)' AS month,
       CASE WHEN pd < DATE '2018-07-08' THEN '1주차' WHEN pd < DATE '2018-07-15' THEN '2주차'
            WHEN pd < DATE '2018-07-22' THEN '3주차' WHEN pd < DATE '2018-07-28' THEN '4주차' ELSE '말일' END AS period,
       COUNT(*) AS n, ROUND(QUANTILE_CONT(lead,0.9),0) AS p90_lead
FROM b7 GROUP BY 1, 2
UNION ALL
SELECT '8월' AS month,
       CASE WHEN pd < DATE '2018-08-08' THEN '1주차' WHEN pd < DATE '2018-08-15' THEN '2주차'
            WHEN pd < DATE '2018-08-22' THEN '3주차' WHEN pd < DATE '2018-08-28' THEN '4주차' ELSE '말일' END AS period,
       COUNT(*) AS n, ROUND(QUANTILE_CONT(lead,0.9),0) AS p90_lead
FROM b8 GROUP BY 1, 2
ORDER BY period, month
""").df()

     month period     n  p90_lead
0  7월(대조군)    1주차  1216      15.0
1       8월    1주차  2127      15.0
2  7월(대조군)    2주차   942      20.0
3       8월    2주차  1810      14.0
4  7월(대조군)    3주차  1584      16.0
5       8월    3주차  1733      11.0
6  7월(대조군)    4주차  1469      14.0
7       8월    4주차   631       7.0
8  7월(대조군)     말일   945      15.0
9       8월     말일    50       2.0

**확인**: 추출시점 상한(2018-10-17)까지 8월 말 주문 기준 약 7주 여유 → 시간부족설 기각. 8/28~31 생존표본(delivered 50건) 소요일 평균 1.76일·최대 2.54일 vs 전체기간 baseline 평균 12.48일·90%ile 23.0일 → 극단적으로 짧음. 2018년 안에서 배송이 꾸준히 빨라지는 장기추세가 있어(1월 90%ile 25일→8월 13일) 8월을 전체기간 평균과 단순비교하면 왜곡됨. 그래서 7월(경계 무관 정상월)을 같은 방식으로 5구간 대조: 7월은 4구간 내내 14~20일 트렌드 없이 오르내리는데 8월은 3주차(8/15~21) 11일부터 이미 정상범위(14~20) 밖으로 벗어남(4주차 7일, 말일 2일). → "8/8~21은 안전, 8/22~만 심각"이라는 축소 해석은 최댓값-90%ile을 잘못 비교하고 연간 개선추세를 반영 안 한 결과로 판단, 기각. 기존 결론(대략 8/15~ 신뢰 불가) 유지.

## 2차 재검토 (2026-09-23, 위 "정정된 해석"의 원인 서술을 다시 정정)
위에서 "아직 배송 중인 주문이 빠진다"고 썼는데, 정작 [보충 B]에서 확인한 8/28~31 결측 13건은 shipped·invoiced가 0건(전부 canceled)이었다 — "아직 배송 중"이라는 원인 서술 자체가 직접 확인한 데이터와 모순된다. 원인을 더 파본다.

In [28]:
# [보충 F, 2026-09-23 2차 재검토] 데이터 추출 시점(최신 도착일) 확인 — "아직 시간이 부족했다"는 설명이 성립하는지
con.execute("SELECT MAX(order_delivered_customer_date) AS latest_delivered_date FROM orders").df()

  latest_delivered_date
0   2018-10-17 13:22:46

In [29]:
# 8/28~31에 남은 delivered 50건의 실제 소요일(시각 단위까지) — "빠른 배송만 살아남았는지" 직접 확인
con.execute("""
SELECT COUNT(*) AS n,
       ROUND(AVG(EPOCH(order_delivered_customer_date - order_purchase_timestamp))/86400, 2) AS avg_days,
       ROUND(MAX(EPOCH(order_delivered_customer_date - order_purchase_timestamp))/86400, 2) AS max_days
FROM orders
WHERE order_purchase_timestamp >= '2018-08-28' AND order_purchase_timestamp < '2018-09-01'
  AND order_delivered_customer_date IS NOT NULL
""").df()

    n  avg_days  max_days
0  50      1.76      2.54

In [30]:
# 8월 5구간 소요일(delivered만) — avg/p90/max를 같이 봐서 "꼬리(max)만 잘렸는지 vs 전체 분포(p90)가 눌렸는지" 구분
con.execute("""
WITH b AS (
  SELECT CAST(order_purchase_timestamp AS DATE) AS pd,
         DATE_DIFF('day', order_purchase_timestamp, order_delivered_customer_date) AS lead
  FROM orders WHERE order_delivered_customer_date IS NOT NULL
    AND order_purchase_timestamp >= '2018-08-01' AND order_purchase_timestamp < '2018-09-01'
)
SELECT CASE WHEN pd < '2018-08-08' THEN '8/1-7' WHEN pd<'2018-08-15' THEN '8/8-14'
            WHEN pd<'2018-08-22' THEN '8/15-21' WHEN pd<'2018-08-28' THEN '8/22-27' ELSE '8/28-31' END AS period,
       COUNT(*) AS n, ROUND(AVG(lead),1) AS avg_lead, ROUND(QUANTILE_CONT(lead,0.9),1) AS p90_lead, MAX(lead) AS max_lead
FROM b GROUP BY period ORDER BY period
""").df()

    period     n  avg_lead  p90_lead  max_lead
0    8/1-7  2127       8.7      15.0        51
1  8/15-21  1733       7.0      11.0        29
2  8/22-27   631       4.8       7.0        10
3  8/28-31    50       1.6       2.0         3
4   8/8-14  1810       8.2      14.0        33

In [31]:
# 7월(정상, 경계와 무관한 대조군)도 같은 방식으로 5구간 분해 — 원래 이렇게 요동치는 게 정상인지 확인
con.execute("""
WITH b AS (
  SELECT CAST(order_purchase_timestamp AS DATE) AS pd,
         DATE_DIFF('day', order_purchase_timestamp, order_delivered_customer_date) AS lead
  FROM orders WHERE order_delivered_customer_date IS NOT NULL
    AND order_purchase_timestamp >= '2018-07-01' AND order_purchase_timestamp < '2018-08-01'
)
SELECT CASE WHEN pd < '2018-07-08' THEN '7/1-7' WHEN pd<'2018-07-15' THEN '7/8-14'
            WHEN pd<'2018-07-22' THEN '7/15-21' WHEN pd<'2018-07-28' THEN '7/22-27' ELSE '7/28-31' END AS period,
       COUNT(*) AS n, ROUND(AVG(lead),1) AS avg_lead, ROUND(QUANTILE_CONT(lead,0.9),1) AS p90_lead, MAX(lead) AS max_lead
FROM b GROUP BY period ORDER BY period
""").df()

    period     n  avg_lead  p90_lead  max_lead
0    7/1-7  1216       8.2      15.0        78
1  7/15-21  1584       9.3      16.0        68
2  7/22-27  1469       8.2      14.0        67
3  7/28-31   945       8.0      15.0        64
4   7/8-14   942      11.1      20.0        68

In [32]:
# 2018년 월별 소요일 추이 — 8월 전체가 낮게 나오는 게 "연중 배송 개선 추세" 때문인지 확인(비교 기준선 자체를 검증)
con.execute("""
WITH b AS (
  SELECT DATE_TRUNC('month', order_purchase_timestamp) AS m,
         DATE_DIFF('day', order_purchase_timestamp, order_delivered_customer_date) AS lead
  FROM orders WHERE order_delivered_customer_date IS NOT NULL
)
SELECT m, COUNT(*) AS n, ROUND(AVG(lead),1) AS avg_lead, ROUND(QUANTILE_CONT(lead,0.9),1) AS p90_lead
FROM b WHERE m >= '2018-01-01' AND m < '2018-09-01'
GROUP BY m ORDER BY m
""").df()

           m     n  avg_lead  p90_lead
0 2018-01-01  7069      14.0      25.0
1 2018-02-01  6556      16.9      31.0
2 2018-03-01  7003      16.2      32.0
3 2018-04-01  6798      11.4      21.0
4 2018-05-01  6749      11.3      21.0
5 2018-06-01  6096       9.2      16.0
6 2018-07-01  6156       8.9      16.0
7 2018-08-01  6351       7.7      13.0

**2차 정정된 해석**
- 데이터 추출 시점(= 전체에서 관측되는 최신 도착일) 2018-10-17. 8/31 구매 기준으로도 47일 여유가 있어 "시간이 부족해서 아직 결과가 없다"는 설명은 액면 그대로는 성립하기 어려움
- 8/28~31에 남은 delivered 50건의 실제 소요일: **평균 1.76일, 최대 2.54일**(분석기간 전체 평균 12.5일, p90 23일과 비교하면 극단적으로 짧음) → 정상적인 소요시간(대략 8~16일)을 가진 주문은 이 구간에 단 한 건도 안 남고, 예외적으로 1~3일 만에 끝난 극소수만 살아남음
- **범위 재검증(중요 — 앞서 낸 "8/15~"라는 경계가 맞는지 다시 확인)**: 8월 전체가 원래 연중 배송 개선 추세(2018-01 p90 25일 → 2018-08 p90 13일)로 다른 달보다 짧게 나오는 게 정상이라, "8월 vs 전체 20개월 평균"으로 비교하면 착시가 생길 수 있음. 그래서 **경계와 무관한 7월을 같은 방식(5구간)으로 쪼개 대조군으로 사용**:
  - 7월(정상, 트렌드 없음): 1주 p90 15일 / 2주 20일 / 3주 16일 / 4주 14일 / 말일 15일 — 14~20일 사이에서 요동, 월말로 갈수록 줄어드는 패턴 없음
  - 8월(비교 대상): 1주 p90 15일 / 2주 14일 / **3주 11일 ← 7월 대조군 범위(14~20)를 벗어나기 시작** / 4주 7일 / 말일 2일
  - **결론: 8/15~21부터 이미 7월 대조군 범위를 벗어남.** "8/8~21은 지장 없고 8/22~만 심각하다"는 식으로 범위를 8/22~로 좁히는 건 과함 — max(최댓값)와 p90(대표값)을 섞어 비교하면 착시가 생기고, 제대로 대조군(7월)을 세워보면 8/15부터 이상 신호가 이미 나타남. **기존 범위(대략 8/15~) 유지가 타당**
- 원인(추정, 미검증): "정상 소요시간 주문이 이 구간 근처에서 canceled로 무더기 종결" 또는 "이 시점 근처의 주문 자체가 스냅샷/큐레이션 경계에 걸려 있음"이 유력한 가설이나, 이 데이터셋만으로 정확한 매커니즘(운영상 자동취소 vs 공개용 데이터 정리 관행 등)을 확정할 근거는 부족함 — **"아직 배송 중이라 절단됐다"는 원인 서술은 폐기**하고 "canceled로 종결됐고 남은 생존 표본이 비정상적으로 빠른 건만 남아 late율이 왜곡됨"으로 서술을 교체. 실질적 액션(8월 후반 late율을 트렌드에 그대로 쓰지 않는다)은 오히려 더 강하게 뒷받침됨

## 결론
- 대표좌표는 우편번호별 **중앙값**으로 확정(D-10). 평균과 10km 넘게 다른 우편번호가 223개, 평균에서 200km 넘는 좌표가 섞인 우편번호가 207개(최대 2,994km)
- 미매칭은 거의 전부 geolocation에 우편번호 자체가 없는 경우(A). 고객 base 주문 265건(0.28%), 셀러 217건(0.23%, 셀러 7곳 중 3곳이 95%), 거리 계산 불가 주문 481건(0.5%). 범위 필터로 인한 미매칭(B)은 고객 1건뿐
- item_lvl 112,650행(조인 전후 동일), distance_km NULL 555건. 거리 중앙값 431.7km, 90% 1,451km, 최대 3,579km로 긴 꼬리. 셀러는 상파울루(SP)에 집중(셀러 59.7%, 아이템 71.3%)
- (2026-09-23 추가, 09-23 재검토로 정정) 날짜 내적 일관성: late 계산에 쓰는 purchase/delivered_customer 컬럼은 위반 0건으로 안전, 다른 조합(166/23/61건)은 Day4 파생변수 작업 전 처리 방침 필요. **우측절단은 실재함(D-17)**: 8월 후반(대략 8/15~, 넓게는 8/8~)으로 갈수록 base에 남은 주문의 late율이 11.1%→0%로 계단식 하락 — 남은(결측 아닌) 주문의 late율 자체가 왜곡된 것으로 확인. 원인은 "아직 배송 중"이 아니라(그 구간 결측은 전부 canceled, 추출시점까지 47일 여유 있었음) "canceled로 종결되고 극단적으로 빠른 소요일(평균 1.76일)의 주문만 생존"하는 현상(원인 자체는 미확정, 2차 재검토). Day4 월별 추이·D-03 테스트기간 결정 시 8월 후반 수치를 실제 추세로 오인하지 않도록 주의

In [33]:
con.close()